### ISSUE TITLE
The given model does not contain the type

### ISSUE THREAD

**Issue by nwoodcl** [smokedlinq/Azure.Functions.Extensions#1]
Hi

Thanks for the code

I followed your example but get the following when implemented in an azure function

System.ArgumentException: 'The given model does not contain the type 'CL.PLA.Models.PLAProduct'. (Parameter 'elementClrType')'

At line in the ODataBinding class
"var queryContext = new ODataQueryContext(_context.Model, _type, new Microsoft.AspNet.OData.Routing.ODataPath());"

Is there something that I could be missing here?

Thanks

**Comment by smokedlinq** [comment]
What did the odata query string look like? Also what does the PLAProduct look like?

I haven't migrated over [my sample app from the old repo](https://github.com/smokedlinq/Microsoft.Azure.WebJobs.Extensions.OData/blob/master/app/GetProductsHttp.cs) yet, check this out to see if you are missing any of the implementation / setup.

**Comment by chrispellett** [comment]
I had the same issue and it was because I hadn't configured the EntitySet for my model. The relevant file in the sample repo is: https://github.com/smokedlinq/Microsoft.Azure.WebJobs.Extensions.OData/blob/master/app/Startup.cs (following this fixed it for me).
