### ISSUE TITLE
Enable count in OData Response

### ISSUE THREAD

**Issue by murugappanm** [smokedlinq/Azure.Functions.Extensions#2]
Hi,
Thanks for the package. Is there a way to get the count in the OData response? I would like to get the count of items that matches the given OData filters so that I can use that count to effectively paginate in my wasm blazor application grid.

Please let me know if you need more context.

Thank you in advance.

**Comment by smokedlinq** [comment]
I took a look quickly but nothing obvious is showing up, I'll dig deeper and get back to you.

**Comment by jacobjohnston** [comment]
I spent a good few hours beating my head over this one. In the end, I could not get MapODataServiceRoute to work in the context of Azure Functions. I did, however, find out that you could manually get at the values of Count, NextLink, etc. via the odataRequest object. Use odataRequest.ODataFeature() to retrieve all of that information.

**Comment by mrmiggles** [comment]
@jacobjohnston can you elaborate on how you retrieved that information? small code sample?

**Comment by smokedlinq** [comment]
FYI I'm stopping work on this and shifting to v8 in dotnet-isolated when I can ...
