### ISSUE TITLE
Odata context in response body

### ISSUE THREAD

**Issue by Bandgren** [smokedlinq/Azure.Functions.Extensions#3]
Hi! Thanks for this package @smokedlinq !

But im not getting it work work with the `PageSize`.

When i try to apply this `EnableQuery` option to the sample code in this repo:
```
[EnableQuery(AllowedQueryOptions = AllowedQueryOptions.All, PageSize = 1)]
```

With this option what i understand i should get 1 product back and a `nextLink` attribute in the odata response but im not getting that back? Is it something im doing wrong here or is this not supported in this nuget package?

**Comment by smokedlinq** [comment]
I'm stopping work on this version, if I pursue upgrading this to v8 I'll be doing it in dotnet-isolated.
