### ISSUE TITLE
Support  OData v.8 

### ISSUE THREAD

**Issue by Tanddant** [smokedlinq/Azure.Functions.Extensions#7]
It appears that after Microsoft update the OData Package to version 8 which includes support for things like $seach.
However this package has a reference to Microsoft.AspNetCore.OData Version 7.5.1.

It appears that Microsoft renamed to namespace of some components causing it to not be possible to just simple install the newer package and be off to the races.

Any chance you'll update this package to version 8?

**Comment by smokedlinq** [comment]
Looks like they really revamped the odata packages ... I'll have to take a look but it's not as easy as just replace the namespaces as many classes and types have changed. What I would prefer to do at this point is make a plugin for dotnet-isolated workers as that is the future for functions and has some extensibility for request processing, though I need them to release the custom converter support for extensions first.
